# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64d23ddc4928053e144496715948bbea"
application_url = "https://zenloop-survey-plugin.onrender.com"
embedded = true
name = "Zenloop-Surveys"
handle = "zenloop-surveys-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/gdpr"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://zenloop-survey-plugin.onrender.com/auth/callback",
  "https://zenloop-survey-plugin.onrender.com/auth/shopify/callback",
  "https://zenloop-survey-plugin.onrender.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-94f6870c.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
